### ISSUE TITLE
Cannot pass in template file uri to deployment profile

### ISSUE THREAD

**Issue by suhuruli** [michaelfery/vscode-sf-mesh-tools#4]
How do I pass in the template file or uri to the create deployment command?

**Comment by michaelfery** [comment]
For now, the command creates a deployment file filled with default values set in [extension settings](https://github.com/michaelfery/vscode-sf-mesh-tools#configuration). 
I'm working on prompting user the type (path or uri) and the path/uri value before generating the deployment file.
A part of the job is done as the method CreateDeploymentProfile accepts templateFileUri and templateFilePath as parameters.

**Comment by michaelfery** [comment]
Resolved with PR #9
