### ISSUE TITLE
Create application does not work

### ISSUE THREAD

**Issue by suhuruli** [michaelfery/vscode-sf-mesh-tools#7]
I installed the VS Code plugin first then instlaled the yeoman generator. The create application command runs and does not do anything. It does not seem to prompt me for any information.

**Comment by michaelfery** [comment]
I submitted a [PR for explicit output error when Yeoman Mesh generator cannot be found](https://github.com/michaelfery/vscode-sf-mesh-tools/pull/8).
However I tried to install extension, reload VSCode, install Yo generator and then use the command. It worked even if the first launch of Yo generator takes time.
Could you please tell what steps you followed so I can reproduce the problem please ?

**Comment by michaelfery** [comment]
As Mikkel indicated in the referenced issue, the command creates or edit the ARM template in a 'deploy' folder in the current workspace. We should probably work on a prompt to let the user choose the destination folder.

**Comment by michaelfery** [comment]
A PR for adding an explicit error when no workspace is opened has been merged in michaelfery/vscode-sf-mesh-tools#10

**Comment by suhuruli** [comment]
Hey thanks Michael!
